### ISSUE TITLE
Convert Qiita flavored markdown to PDF and/or HTML 

### ISSUE THREAD

**Issue by ryokat3** [ryokat3/vscode-qiita-markdown-preview#3]
Original comment on Qiita

https://qiita.com/ryokat3/items/fe61d9234be2e147cb7f#comment-a7af9e083ab8be2d8ce6

**Comment by ra1t0** [comment]
@ryokat3 さん、こんにちは。
Qiita記事でコメントさせて頂いた[@rait0](https://qiita.com/rait0)です。

# 伝えたいこと
こちらのイシューに関して対処法を発見しました。

# 謝罪
まず、調べればすぐに出てくる内容を質問してしまい申し訳ございませんでした。
また、VSCodeの拡張機能開発に関しては無知のため、こちらのソース修正での実現ではなく
他のVSCode拡張機能を使用した解決方法になっております。

# 解決方法
こちらの拡張機能を使用する事によって対処可能でした。
[https://github.com/manuth/MarkdownConverter](https://github.com/manuth/MarkdownConverter)

上記の拡張機能ではプレビューをそのままPDFに変換してくれるようです。
変換結果のPDFをこのコメントに添付します。
[memo.pdf](https://github.com/ryokat3/vscode-qiita-markdown-preview/files/8054961/memo.pdf)

**Comment by ryokat3** [comment]
@ra1t0 さん、

ご報告有難うございます。是非これからもご要望やご意見などは気軽になさってください。拡張機能のご報告までしていただいて、感謝でしかありません。ご紹介いただいた VSCode の拡張機能については Qiita の記事の中で紹介させていただきました。貴重な情報ありがとうございました。
